optim_type: adamw
lr_choice: layerwise_decay
lr_schedule: cosine_decay
lr: 0.0001
lr_decay: 0.8
end_lr: 0
lr_mult: 1
weight_decay: 0.001
warmup_steps: 0.1
validation_metric_name: roc_auc
custom_metric_func: null
efficient_finetune: null
mixup_fn: null
mixup_off_epoch: 5
aug_optimizer: true
aug_turn_on: true
aug_lr: 0.0001
aug_optim_type: adam
aug_weight_decay: 1.0e-05
grad_steps: 4
